resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/6.yaml

packages:
- xmonad
- xmonad-contrib

# extra-deps: []

# Override default flag values for local packages and extra-deps
# flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# arch: x86_64
#
