# Located at "~/.bashrc".

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

alias ls="ls --color=auto"
PS1="[\u@\h \W]\$ "

# Load NVM.
source /usr/share/nvm/init-nvm.sh

