name: Sync to Codeberg

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  codeberg:
    if: github.repository == 'Vexcited/dotfiles'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Ximaz/repository-mirroring-action@main
        with:
          target_repo_url: "git@codeberg.org:Vexcited/dotfiles.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
          ssh_private_key_passphrase: ${{ secrets.CODEBERG_SSH_PASSPHRASE }}
